openapi: 3.0.2
components:
  paths:
    gravity:
      post:
        summary: Run gravity
        tags:
          - Actions
        operationId: "action_gravity"
        description: |
          Update Pi-hole's adlists by running `pihole -g`. The output of the process is streamed with chunked encoding.
        responses:
          '200':
            description: OK
            content:
              text/plain:
                schema:
                  type: string
                  example: |
                      [i] Neutrino emissions detected...

                      [✓] Pulling blocklist source list into range

                      [i] Preparing new gravity database...
                      [✓] Preparing new gravity database
                      [i] Using libz compression

                      [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
                      [✓] Status: Retrieval successful
                      [i] Imported 172502 domains, ignoring 3 non-domain entries
                          Sample of non-domain entries:
                            - 0.0.0.0
                            - fe
                            - ff
                      [i] List stayed unchanged

                      [i] Target: https://v.firebog.net/hosts/AdguardDNS.txt
                      [✓] Status: No changes detected
                      [i] Imported 47225 domains

                      [✓] Creating new gravity databases
                      [✓] Storing downloaded domains in new gravity database
                      [✓] Building tree
                      [✓] Swapping databases
                      [✓] The old database remains available.
                      [i] Number of gravity domains: 219727 (215440 unique domains)
                      [i] Number of exact blacklisted domains: 0
                      [i] Number of regex blacklist filters: 2
                      [i] Number of exact whitelisted domains: 0
                      [i] Number of regex whitelist filters: 0
                      [✓] Cleaning up stray matter

                      [✓] FTL is listening on port
                         [✓] UDP (IPv4)
                         [✓] TCP (IPv4)
                         [✓] UDP (IPv6)
                         [✓] TCP (IPv6)

                      [✓] Pi-hole blocking is enabled
          '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  $ref: 'common.yaml#/components/errors/unauthorized'
    reboot:
      post:
        summary: Reboot the system
        tags:
          - Actions
        operationId: "action_reboot"
        description: |
          Reboots the system Pi-hole is running on. Note that this should be done as a last-resort only as it will forcefully interrupt all currently running processes.
        responses:
          '200':
            description: OK
          '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  $ref: 'common.yaml#/components/errors/unauthorized'
    poweroff:
      post:
        summary: Poweroff the system
        tags:
          - Actions
        operationId: "action_poweroff"
        description: |
          Halts and powers off the system Pi-hole is running on. Note that this should be done as a last-resort only as it will forcefully interrupt all currently running processes.
        responses:
          '200':
            description: OK
          '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  $ref: 'common.yaml#/components/errors/unauthorized'
