openapi: 3.0.2
components:
  paths:
    config:
      get:
        summary: Get current configuration of your Pi-hole
        tags:
          - "FTL information"
        operationId: "get_config"
        description: |
          This API hook returns infos about the config of your Pi-hole.
        parameters:
          - $ref: 'config.yaml#/components/parameters/detailed'
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: 'config.yaml#/components/schemas/config'
                examples:
                  config:
                    $ref: 'config.yaml#/components/examples/config'
          '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  $ref: 'common.yaml#/components/errors/unauthorized'
      patch:
        summary: Change configuration of your Pi-hole
        tags:
          - "FTL information"
        operationId: "patch_config"
        description: |
          This API hook allows to modify the config of your Pi-hole. This endpoint supports changing multiple properties at once when you specify several in the payload. See examples below.
        requestBody:
          description: Callback payload
          content:
            application/json:
              schema:
                $ref: 'config.yaml#/components/schemas/config'
              examples:
                config_one:
                  $ref: 'config.yaml#/components/examples/config_one'
                config_two:
                  $ref: 'config.yaml#/components/examples/config_two'
                config:
                  $ref: 'config.yaml#/components/examples/config'
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: 'config.yaml#/components/schemas/config'
                examples:
                  config:
                    $ref: 'config.yaml#/components/examples/config'
          '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  $ref: 'common.yaml#/components/errors/unauthorized'
  schemas:
    config:
      type: object
      properties:
        config:
          type: object
          properties:
            dns:
              type: object
              properties:
                CNAMEdeepInspect:
                  type: boolean
                blockESNI:
                  type: boolean
                EDNS0ECS:
                  type: boolean
                ignoreLocalhost:
                  type: boolean
                showDNSSEC:
                  type: boolean
                analyzeAAAA:
                  type: boolean
                analyzeOnlyAandAAAA:
                  type: boolean
                piholePTR:
                  type: string
                replyWhenBusy:
                  type: string
                blockTTL:
                  type: integer
                port:
                  type: integer
                blocking:
                  type: object
                  properties:
                    active:
                      type: boolean
                    mode:
                      type: string
                specialDomains:
                  type: object
                  properties:
                    mozillaCanary:
                      type: boolean
                    iCloudPrivateRelay:
                      type: boolean
                reply:
                  type: object
                  properties:
                    host:
                      type: object
                      properties:
                        overwrite_v4:
                          type: boolean
                        overwrite_v6:
                          type: boolean
                        IPv4:
                          type: string
                        IPv6:
                          type: string
                    blocking:
                      type: object
                      properties:
                        overwrite_v4:
                          type: boolean
                        overwrite_v6:
                          type: boolean
                        IPv4:
                          type: string
                        IPv6:
                          type: string
                rateLimit:
                  type: object
                  properties:
                    count:
                      type: integer
                    interval:
                      type: integer
            resolver:
              type: object
              properties:
                resolveIPv4:
                  type: boolean
                resolveIPv6:
                  type: boolean
                networkNames:
                  type: boolean
                refreshNames:
                  type: string
            database:
              type: object
              properties:
                DBimport:
                  type: boolean
                DBexport:
                  type: boolean
                maxHistory:
                  type: integer
                maxDBdays:
                  type: integer
                DBinterval:
                  type: integer
                network:
                  type: object
                  properties:
                    parseARPcache:
                      type: boolean
                    expire:
                      type: integer
            api:
              type: object
              properties:
                localAPIauth:
                  type: boolean
                prettyJSON:
                  type: boolean
                sessionTimeout:
                  type: integer
                pwhash:
                  type: string
                exclude_clients:
                  type: array
                  items:
                    type: string
                exclude_domains:
                  type: array
                  items:
                    type: string
            http:
              type: object
              properties:
                domain:
                  type: string
                acl:
                  type: string
                port:
                  type: string
                paths:
                  type: object
                  properties:
                    webroot:
                      type: string
                    webhome:
                      type: string
                interface:
                  type: object
                  properties:
                    boxed:
                      type: boolean
                    theme:
                      type: string
            files:
              type: object
              properties:
                log:
                  type: string
                pid:
                  type: string
                database:
                  type: string
                gravity:
                  type: string
                macvendor:
                  type: string
                setupVars:
                  type: string
                http_info:
                  type: string
                ph7_error:
                  type: string
            misc:
              type: object
              properties:
                nice:
                  type: integer
                delay_startup:
                  type: integer
                addr2line:
                  type: boolean
                privacylevel:
                  type: integer
                temp_limit:
                  type: number
                check:
                  type: object
                  properties:
                    load:
                      type: boolean
                    shmem:
                      type: integer
                    disk:
                      type: integer
            debug:
              type: object
              properties:
                database:
                  type: boolean
                networking:
                  type: boolean
                locks:
                  type: boolean
                queries:
                  type: boolean
                flags:
                  type: boolean
                shmem:
                  type: boolean
                gc:
                  type: boolean
                arp:
                  type: boolean
                regex:
                  type: boolean
                api:
                  type: boolean
                overtime:
                  type: boolean
                status:
                  type: boolean
                caps:
                  type: boolean
                dnssec:
                  type: boolean
                vectors:
                  type: boolean
                resolver:
                  type: boolean
                edns0:
                  type: boolean
                clients:
                  type: boolean
                aliasclients:
                  type: boolean
                events:
                  type: boolean
                helper:
                  type: boolean
                config:
                  type: boolean
                extra:
                  type: boolean
                reserved:
                  type: boolean
  examples:
    config:
      summary: The entire configuration
      value:
        config:
          dns:
            CNAMEdeepInspect: true
            blockESNI: true
            EDNS0ECS: true
            ignoreLocalhost: false
            showDNSSEC: true
            analyzeAAAA: true
            analyzeOnlyAandAAAA: false
            piholePTR: PI.HOLE
            replyWhenBusy: ALLOW
            blockTTL: 2
            blocking:
              active: true
              mode: 'NULL'
            specialDomains:
              mozillaCanary: true
              iCloudPrivateRelay: true
            reply:
              host:
                overwrite_v4: false
                overwrite_v6: false
                IPv4: 0.0.0.0
                IPv6: "::"
              blocking:
                overwrite_v4: false
                overwrite_v6: false
                IPv4: 0.0.0.0
                IPv6: "::"
            rateLimit:
              count: 0
              interval: 0
            port: 53
          resolver:
            resolveIPv4: true
            resolveIPv6: true
            networkNames: true
            refreshNames: IPV4_ONLY
          database:
            DBimport: true
            DBexport: true
            maxHistory: 86400
            maxDBdays: 365
            DBinterval: 60
            network:
              parseARPcache: true
              expire: 365
          api:
            localAPIauth: false
            prettyJSON: false
            sessionTimeout: 300
            pwhash: ''
            exclude_clients: [ '1.2.3.4', 'localhost', 'fe80::345' ]
            exclude_domains: [ 'google.de', 'pi-hole.net' ]
          http:
            domain: pi.hole
            acl: "+0.0.0.0/0"
            port: 8080,[::]:8080
            paths:
              webroot: "/var/www/html"
              webhome: "/admin/"
            interface:
              boxed: true
              theme: "default-darker"
          files:
            log: "/var/log/pihole/FTL.log"
            pid: "/run/pihole-FTL.pid"
            database: "/etc/pihole/pihole-FTL.db"
            gravity: "/etc/pihole/gravity.db"
            macvendor: "/etc/pihole/macvendor.db"
            setupVars: "/etc/pihole/setupVars.conf"
            http_info: "/var/log/pihole/HTTP_info.log"
            ph7_error: "/var/log/pihole/PH7.log"
          misc:
            nice: -10
            delay_startup: 10
            addr2line: true
            privacylevel: 0
            temp_limit: 60.0
            check:
              load: true
              shmem: 90
              disk: 90
          debug:
            database: false
            networking: false
            locks: false
            queries: false
            flags: false
            shmem: false
            gc: false
            arp: false
            regex: false
            api: false
            overtime: false
            status: false
            caps: false
            dnssec: false
            vectors: false
            resolver: false
            edns0: false
            clients: false
            aliasclients: false
            events: false
            helper: false
            config: false
            extra: false
            reserved: false
    config_one:
      summary: One option
      value:
        config:
          dns:
            CNAMEdeepInspect: true
    config_two:
      summary: Two options
      value:
        config:
          dns:
            specialDomains:
              mozillaCanary: true
          misc:
            nice: -10
  parameters:
    detailed:
      name: detailed
      in: query
      description: Return detailed information about the configuration
      required: false
      schema:
        type: boolean
        default: false
        example: false
