openapi: 3.0.2
components:
  paths:
    leases:
      get:
        summary: Get currently active DHCP leases
        tags:
          - "FTL information"
        operationId: "get_dhcp"
        description: |
          This API hook returns the currently active DHCP leases.
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: 'dhcp.yaml#/components/schemas/leases'
          '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  $ref: 'common.yaml#/components/errors/unauthorized'
  schemas:
    leases:
      type: object
      properties:
        leases:
          type: array
          description: DHCP leases
          items:
            type: object
            properties:
              expires:
                type: integer
                description: Expiration time
                example: 1675671991
              name:
                type: string
                description: Hostname
                example: "raspberrypi"
              hwaddr:
                type: string
                description: Hardware (MAC) address
                example: "00:00:00:00:00:00"
              ip:
                type: string
                description: IP address
                example: "192.168.2.111"
              clientid:
                type: string
                description: Client ID
                example: "00:00:00:00:00:00"