openapi: 3.0.2
components:
  paths:
    blocking:
      summary: Modify blocking status
      get:
        summary: Get current blocking status
        tags:
          - DNS control
        operationId: "get_blocking"
        security:
          - sidHeader: []
        description: |
          The property `timer` may contain additional details concerning a temporary en-/disabling.
          It is `null` when no timer is active (the current status is permanent).
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  allOf:
                    - $ref: 'dns.yaml#/components/schemas/blocking'
                    - $ref: 'dns.yaml#/components/schemas/timer'
      post:
        summary: Change current blocking status
        tags:
          - DNS control
        operationId: "set_blocking"
        description: |
          Change the current blocking mode by setting `blocking` to the desired value.
          The optional `timer` object may used to set a timer. Once this timer elapsed, the opposite blocking mode is automatically set.
          For instance, you can request `{blocking: true, timer: 60}` to disable Pi-hole for one minute.
          Blocking will be automatically resumed afterwards.

          You can terminate a possibly running timer by setting `timer` to `null` (the set mode becomes permanent).
        requestBody:
          description: Callback payload
          content:
            'application/json':
              schema:
                allOf:
                  - $ref: 'dns.yaml#/components/schemas/blocking'
                  - $ref: 'dns.yaml#/components/schemas/timer'
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  allOf:
                    - $ref: 'dns.yaml#/components/schemas/blocking'
                    - $ref: 'dns.yaml#/components/schemas/timer'
          '400':
            description: Bad request
            content:
              application/json:
                schema:
                  oneOf:
                  - $ref: 'dns.yaml#/components/schemas/errors/no_payload'
                  - $ref: 'dns.yaml#/components/schemas/errors/item_missing'
          '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  $ref: 'common.yaml#/components/errors/unauthorized'
    cache:
      get:
        summary: Get cache info
        tags:
          - Metrics
        operationId: "get_cacheinfo"
        description: |
          This API hook returns live information about the DNS cache usage.
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: 'dns.yaml#/components/schemas/cache'
                examples:
                  cache:
                    $ref: 'dns.yaml#/components/examples/cache'
          '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  $ref: 'common.yaml#/components/errors/unauthorized'

  schemas:
    blocking:
      type: object
      properties:
        blocking:
          type: boolean
          description: Blocking status
          example: true
    timer:
      type: object
      properties:
        timer:
          type: integer
          description: Remaining seconds until blocking mode is automatically changed
          nullable: true
          example: 15

    cache:
      type: object
      properties:
        cache:
          type: object
          description: Cache information
          properties:
            size:
              type: integer
              description: Cache size
            inserted:
              type: integer
              description: Number of inserted entries
            evicted:
              type: integer
              description: Number of evicted entries
            expired:
              type: integer
              description: Number of expired entries
            immortal:
              type: integer
              description: Number of immortal entries
            valid:
              type: object
              description: Number of valid entries
              properties:
                ipv4:
                  type: integer
                  description: Number of valid IPv4 entries
                ipv6:
                  type: integer
                  description: Number of valid IPv6 entries
                cname:
                  type: integer
                  description: Number of valid CNAME entries
                srv:
                  type: integer
                  description: Number of valid SRV entries
                ds:
                  type: integer
                  description: Number of valid DS entries
                dnskey:
                  type: integer
                  description: Number of valid DNSKEY entries
                other:
                  type: integer
                  description: Number of valid other entries
    errors:
      item_missing:
        type: object
        description: Item to be modified is missing
        properties:
          error:
            type: object
            properties:
              key:
                type: string
                description: "Machine-readable error type"
                example: "body_error"
              message:
                type: string
                description: "Human-readable error message"
                example: "No \\\"blocking\\\" boolean in body data"
              hint:
                type: string
                nullable: true
                description: "Additional data (if available)"
                example: null
      no_payload:
        type: object
        description: No JSON payload found
        properties:
          error:
            type: object
            properties:
              key:
                type: string
                description: "Machine-readable error type"
                example: "bad_request"
              message:
                type: string
                description: "Human-readable error message"
                example: "Invalid request body data (no valid JSON)"
              hint:
                type: string
                nullable: true
                description: "Additional data (if available)"
                example: null
  examples:
    cache:
      summary: Cache info
      value:
        cache:
          size: 10000
          inserted: 4060
          evicted: 0
          expired: 0
          immortal: 0
          valid:
            ipv4: 212
            ipv6: 61
            cname: 14
            srv: 0
            ds: 60
            dnskey: 35
            other: 14
