openapi: 3.0.2
info:
  title: Pi-hole API
  version: "6.0"
  contact:
    name: Pi-hole API Support
    url: https://discourse.pi-hole.net
  license:
    name: European Union Public Licence (EUPL)
    url: https://joinup.ec.europa.eu/community/eupl/og_page/eupl
  description: >
    The Pi-hole API is organized around [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer).
    Our API has predictable resource-oriented URLs, accepts and returns reliable UTF-8 [JavaScript Object Notation (JSON)-encoded](http://www.json.org/) data for all API responses, and uses standard HTTP response codes and verbs.

    Most (but not all) endpoints require authentication.
    API endpoints requiring authentication will fail with code `401 Unauthorized` when used outside a valid session.
servers:
  - url: 'http://{url}:{port}/{path}'
    variables:
      url:
        description: URL or address of your Pi-hole
        default: pi.hole
      port:
        description: Port of your Pi-hole's API
        default: "8080"
      path:
        description: Path where your Pi-hole's API is hosted
        default: api

tags:
  - name: "Authentication"
    description: Methods used to authentaticate with the API
  - name: "Metrics"
    description: Methods used to get usage data from your Pi-hole
  - name: "DNS control"
    description: Methods used to control the behavior of your Pi-hole
  - name: "Group management"
    description: Methods used to manage groups on your Pi-hole
  - name: "Domain management"
    description: Methods used to manage domains on your Pi-hole
  - name: "Client management"
    description: Methods used to manage clients on your Pi-hole
  - name: "List management"
    description: Methods used to manage lists on your Pi-hole
  - name: "FTL information"
    description: Methods used to gather advanced data from your Pi-hole
  - name: "Pi-hole configuration"
    description: Methods used to configure your Pi-hole
  - name: "Network information"
    description: Methods used to gather advanced information about your network

paths:
  /auth:
    $ref: 'auth.yaml#/components/paths/auth'

  /stats/summary:
    $ref: 'stats.yaml#/components/paths/summary'

  /stats/database/summary:
    $ref: 'stats.yaml#/components/paths/database_summary'

  /stats/upstreams:
    $ref: 'stats.yaml#/components/paths/upstreams'

  /stats/database/upstreams:
    $ref: 'stats.yaml#/components/paths/database_upstreams'

  /stats/top_domains:
    $ref: 'stats.yaml#/components/paths/top_domains'

  /stats/database/top_domains:
    $ref: 'stats.yaml#/components/paths/database_top_domains'

  /stats/top_clients:
    $ref: 'stats.yaml#/components/paths/top_clients'

  /stats/database/top_clients:
    $ref: 'stats.yaml#/components/paths/database_top_clients'

  /stats/query_types:
    $ref: 'stats.yaml#/components/paths/query_types'

  /stats/database/query_types:
    $ref: 'stats.yaml#/components/paths/database_query_types'

  /stats/recent_blocked:
    $ref: 'stats.yaml#/components/paths/recent_blocked'

  /history:
    $ref: 'history.yaml#/components/paths/history'

  /history/clients:
    $ref: 'history.yaml#/components/paths/clients'

  /history/database:
    $ref: 'history.yaml#/components/paths/database_history'

  /history/database/clients:
    $ref: 'history.yaml#/components/paths/database_clients'

  /queries:
    $ref: 'queries.yaml#/components/paths/queries'

  /queries/suggestions:
    $ref: 'queries.yaml#/components/paths/suggestions'

  /dns/blocking:
    $ref: 'dns.yaml#/components/paths/blocking'

  /dns/cache:
    $ref: 'dns.yaml#/components/paths/cache'

  /domains/{type}/{kind}/{domain}:
    $ref: 'domains.yaml#/components/paths/type_kind_domain'

  /domains/{type}/{kind}:
    $ref: 'domains.yaml#/components/paths/type_kind'

  /groups/{name}:
    $ref: 'groups.yaml#/components/paths/name'

  /groups:
    $ref: 'groups.yaml#/components/paths/direct'

  /clients/{client}:
    $ref: 'clients.yaml#/components/paths/client'

  /clients:
    $ref: 'clients.yaml#/components/paths/direct'

  /lists/{list}:
    $ref: 'lists.yaml#/components/paths/list'

  /lists:
    $ref: 'lists.yaml#/components/paths/direct'

  /ftl/client:
    $ref: 'ftl.yaml#/components/paths/client'

  /ftl/sysinfo:
    $ref: 'ftl.yaml#/components/paths/sysinfo'

  /ftl/dbinfo:
    $ref: 'ftl.yaml#/components/paths/dbinfo'

  /logs/dnsmasq:
    $ref: 'logs.yaml#/components/paths/logs/dnsmasq'

  /logs/ftl:
    $ref: 'logs.yaml#/components/paths/logs/ftl'

  /logs/http:
    $ref: 'logs.yaml#/components/paths/logs/http'

  /logs/ph7:
    $ref: 'logs.yaml#/components/paths/logs/ph7'

  /endpoints:
    $ref: 'endpoints.yaml#/components/paths/endpoints'

  /config:
    $ref: 'config.yaml#/components/paths/config'

  /config/{element}:
    $ref: 'config.yaml#/components/paths/config_elem'

  /config/{element}/{value}:
    $ref: 'config.yaml#/components/paths/config_elem_value'

  /network/devices:
    $ref: 'network.yaml#/components/paths/devices'

  /network/gateway:
    $ref: 'network.yaml#/components/paths/gateway'

  /network/interfaces:
    $ref: 'network.yaml#/components/paths/interfaces'

  /version:
    $ref: 'version.yaml#/components/paths/version'

components:
  securitySchemes:
    sidHeader:
      type: apiKey
      name: sid
      description: SID used for secured endpoints
      in: header