openapi: 3.0.2
components:
  paths:
    summary:
      get:
        summary: Get overview of Pi-hole activity
        tags:
          - Metrics
        operationId: "get_metrics_summary"
        description: |
          Request various query, system, and FTL properties
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: 'stats.yaml#/components/schemas/queries'
          '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  $ref: 'common.yaml#/components/errors/unauthorized'

    upstreams:
      get:
        summary: Get metrics about Pi-hole's upstream destinations
        tags:
          - Metrics
        operationId: "get_metrics_upstreams"
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: 'stats.yaml#/components/schemas/upstreams'
          '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  $ref: 'common.yaml#/components/errors/unauthorized'

    database_upstreams:
      get:
        summary: Get metrics about Pi-hole's upstream destinations (database)
        tags:
          - Metrics
        operationId: "get_metrics_upstreams_database"
        parameters:
          - $ref: 'common.yaml#/components/parameters/database/from'
          - $ref: 'common.yaml#/components/parameters/database/until'
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: 'stats.yaml#/components/schemas/upstreams'
          '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  $ref: 'common.yaml#/components/errors/unauthorized'

  schemas:
    queries:
      type: object
      properties:
        queries:
          type: object
          properties:
            total:
              type: integer
              description: Total number of queries
              example: 7497
            blocked:
              type: integer
              description: Number of blocked queries
              example: 3465
            percent_blocked:
              type: number
              description: Percent of blocked queries
              example: 34.5
            unique_domains:
              type: integer
              description: Number of unique domains FTL knows
              example: 445
            forwarded:
              type: integer
              description: Number of queries that have been forwarded upstream
              example: 4574
            cached:
              type: integer
              description: Number of queries replied to from cache or local configuration
              example: 9765
            types:
              type: object
              description: Number of individual queries
              properties:
                A:
                  type: integer
                  description: Type A queries
                  example: 3643
                AAAA:
                  type: integer
                  description: Type AAAA queries
                  example: 123
                ANY:
                  type: integer
                  description: Type ANY queries
                  example: 3423
                SRV:
                  type: integer
                  description: Type SRV queries
                  example: 345
                SOA:
                  type: integer
                  description: Type SOA queries
                  example: 7567
                PTR:
                  type: integer
                  description: Type PTR queries
                  example: 456
                TXT:
                  type: integer
                  description: Type TXT queries
                  example: 85
                NAPTR:
                  type: integer
                  description: Type NAPTR queries
                  example: 346
                MX:
                  type: integer
                  description: Type MX queries
                  example: 457
                DS:
                  type: integer
                  description: Type DS queries
                  example: 456
                RRSIG:
                  type: integer
                  description: Type RRSIG queries
                  example: 345
                DNSKEY:
                  type: integer
                  description: Type DNSKEY queries
                  example: 55
                NS:
                  type: integer
                  description: Type NS queries
                  example: 868
                SVCB:
                  type: integer
                  description: Type SVCB queries
                  example: 645
                HTTPS:
                  type: integer
                  description: Type HTTPS queries
                  example: 4
                OTHER:
                  type: integer
                  description: Queries of remaining types
                  example: 845
            replies:
              type: object
              description: Number of individual replies
              properties:
                NODATA:
                  type: integer
                  description: NODATA responses
                  example: 14
                NXDOMAIN:
                  type: integer
                  description: NXDOMAIN responses
                  example: 45
                CNAME:
                  type: integer
                  description: CNAME responses
                  example: 76
                IP:
                  type: integer
                  description: IP responses
                  example: 85
                text:
                  type: integer
                  description: text responses
                  example: 16
    upstreams:
      type: object
      properties:
        upstreams:
          type: array
          description: Array of upstream destinations
          items:
            type: object
            properties:
              ip:
                type: string
                description: Upstream destination's IP address (can be either IPv4 or IPv6)
                nullable: true
                example: "127.0.0.1"
              name:
                type: string
                description: Upstream destination's hostname (if available)
                nullable: true
                example: "localhost"
              port:
                type: integer
                description: Upstream destination's destination port (-1 if not applicable, e.g., for the local chace)
                example: 53
              count:
                type: integer
                description: Number of queries this upstream destination has been used for
                example: 65445
              statistics:
                type: object
                properties:
                  response:
                    type: string
                    description: Average response time of this upstream destination in seconds (0 if not applicable)
                    example: 0.0254856
                  variance:
                    type: string
                    description: Standard deviation of the average response time (0 if not applicable)
                    example: 0.02058
        forwarded_queries:
          type: integer
          description: Number of forwarded queries
          example: 6379
        total_queries:
          type: integer
          description: Total number of queries
          example: 29160