openapi: 3.0.2
components:
  paths:
    version:
      get:
        summary: Get Pi-hole version
        tags:
          - "FTL information"
        operationId: "get_version"
        description: |
          Request versions of the individual Pi-hole components
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: 'version.yaml#/components/schemas/version'

  schemas:
    version:
      type: object
      properties:
        version:
          type: object
          properties:
            core:
              type: object
              properties:
                local:
                  type: object
                  properties:
                    branch:
                      type: string
                      description: Local Pi-hole Core branch
                      example: "development"
                    version:
                      type: string
                      description: Local Pi-hole Core version
                      example: "v6.1"
                    hash:
                      type: string
                      description: Local Pi-hole Core hash
                      example: "955e36a9"
                remote:
                  type: object
                  properties:
                    version:
                      type: string
                      description: Remote (Github) Pi-hole Core version
                      example: "v6.1"
                    hash:
                      type: string
                      description: Remote (Github) Pi-hole Core hash
                      example: "955e36a9"
            web:
              type: object
              properties:
                local:
                  type: object
                  properties:
                    branch:
                      type: string
                      description: Local Pi-hole Web branch
                      example: "devel"
                    version:
                      type: string
                      description: Local Pi-hole Web version
                      example: "v6.1"
                    hash:
                      type: string
                      description: Local Pi-hole Web hash
                      example: "f69f7e88"
                remote:
                  type: object
                  properties:
                    version:
                      type: string
                      description: Remote (Github) Pi-hole Web version
                      example: "v6.1"
                    hash:
                      type: string
                      description: Remote (Github) Pi-hole Web hash
                      example: "f69f7e88"
            ftl:
              type: object
              properties:
                local:
                  type: object
                  properties:
                    branch:
                      type: string
                      description: Local Pi-hole FTL branch
                      example: "development"
                    version:
                      type: string
                      description: Local Pi-hole FTL version
                      example: "v6.1"
                    hash:
                      type: string
                      description: Local Pi-hole FTL hash
                      example: "64441ed6-dirty"
                    date:
                      type: string
                      description: Build time of your local Pi-hole FTL
                      example: "2023-01-09 20:25:24 +0100"
                remote:
                  type: object
                  properties:
                    version:
                      type: string
                      description: Remote (Github) Pi-hole FTL version
                      example: "v6.1"
                    hash:
                      type: string
                      description: Remote (Github) Pi-hole FTL hash
                      example: "64441ed6"