name: API validation

on: [push]

env:
  CI: true

jobs:
  openapi-validator:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "19.x"

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm test
